### ISSUE TITLE
Besu-Prod - Member-1 node crash

### ISSUE THREAD

**Issue by YounesBM** [ConsenSys/quorum-kubernetes#101]
Hello,

Best wishes for this year 2022.

We are experiencing a problem while deploying Besu in "prod" environment on Azure Kubernetes.
All pods are working properly except for the "member-1" pod which is in "crashLoopBackOff" status.
Apparently, there is a problem in the definition of the Enode URL in the /config/static/static-nodes.json/ file.
On the other hand, we manage to deploy Besu in Dev environment without any problem.

I have prepared a public github repo that explains how to reproduce the bug.
If you want, you can clone it directly and follow the instructions in the README.md :
https://github.com/YounesBM/besu-prod-issue

Problem found:

![Status](https://github.com/YounesBM/besu-prod-issue/blob/main/Pods.JPG?raw=true)

Logs of pod "member-1", container "member-1-besu

![Logs](https://github.com/YounesBM/besu-prod-issue/blob/main/Logs%20member-1-besu.JPG?raw=true)

Can you please help us to fix this problem?

Thank you for your help,

Best Regards,

Younes

**Comment by joshuafernandes** [comment]
Hi @YounesBM 
I've just pushed out #106 which will fix this. I've spun this up afresh on azure without issue. I believe the error was it was reading the public.key and not the enode file which has an extra `0x` in front and that causes it to read the enode incorrectly

Let me know if that works for you

Cheers
Josh

**Comment by YounesBM** [comment]
Hello @joshuafernandes 

Thank you very much for your reply.

I tried to deploy besu again and the member-1 pod does not crash anymore! 💯 

Just one last question. Since a few days, every time I try to connect my private network to Metamask, I get this error:
`kubectl logs besu-node-member-1-0 -c member-1-besu --namespace besu`

![Metamask error](https://github.com/YounesBM/logs-quorum/blob/main/Metamask.JPG?raw=true)

Do you know where this can come from?

Cheers,
Younes

**Comment by joshuafernandes** [comment]
Hi @YounesBM 

Can you confirm normal RPC calls work ok from your local machine?

That's probably a cors specific origin that'll need to be added https://besu.hyperledger.org/en/latest/Reference/CLI/CLI-Syntax/#rpc-http-cors-origins or a specific API that needs to be enabled https://besu.hyperledger.org/en/latest/Reference/CLI/CLI-Syntax/#rpc-http-api

What I'd recommend doing is logging this under hyperledger/besu as an issue with steps to reproduce and we can look at it from there.

Cheers
Josh
