### ISSUE TITLE
Not able to generate keys

### ISSUE THREAD

**Issue by ShubhamKarala** [ConsenSys/quorum-kubernetes#113]
when I use the command "docker run --rm --volume $PWD/ibftSetup/:/opt/besu/data hyperledger/besu:latest operator generate-blockchain-config --config-file=/opt/besu/data/ibftConfigFile.json --to=/opt/besu/data/networkFiles --private-key-file-name=key".

the output error is:
2022-01-26 13:04:12.468+00:00 | main | ERROR | GenerateBlockchainConfig | An error occurred while trying to generate network configuration.
java.io.FileNotFoundException: /opt/besu/data/ibftConfigFile.json (No such file or directory)

I was following the guide on this URL "https://github.com/ConsenSys/quorum-kubernetes/tree/master/playground/kubectl/quorum-besu/ibft2".

**Comment by joshuafernandes** [comment]
Hi @ShubhamKarala thanks for raising this. I'll update the docs to remove this piece. Essentially it is this proccess to create the genesis file and keys https://besu.hyperledger.org/en/latest/Tutorials/Private-Network/Create-IBFT-Network/  and you can create the folder and put the ibftConfigFile.json file there with contents from the tutorial link 

Cheers

**Comment by ShubhamKarala** [comment]
thank you
