### ISSUE TITLE
What are the best practices for increasing the number of tps of my private network (Besu/PoA/Ibft2) on Azure Kubernetes??

### ISSUE THREAD

**Issue by andyafene** [ConsenSys/quorum-kubernetes#124]
Hello,

I'd like to know what are the best practices for increasing the number of tps of my private network (Besu/PoA/Ibft2) on Azure Kubernetes?
Indeed, I was wondering if reducing the block production time and/or increasing the block size was more efficient than adding the number of nodes or validators?

Regards,

**Comment by joshuafernandes** [comment]
Hello @andyafene The two topics are orthogonal.  TPS isn't dependant on number of nodes or validators. It depends (and is a tradeoff) on algorithm, block size, gas limits and block time. It isn't dependant on the infra (k8s, vms, ec2 etc) but more on how you configure the genesis and your node topology.

I'd suggest asking these on the Discord channels as these are more relevant there than here.
