### ISSUE TITLE
Peers are not connected after deployment of nodes to AKS with 'prod' helm charts.

### ISSUE THREAD

**Issue by naoki4** [ConsenSys/quorum-kubernetes#125]
When quorum nodes are deployed to the Azure Kubenetes Service with 'prod' helm charts,the nodes are not connected.
It seems that the syntax of enodes list of the peers in the file "static-node.json" created at the deployment is not correct.

The format of enodes in the file is as follows (enode addresses are not contained):

>   enode://@faqn-or-ip-address:port-number
>   (ex. enode://@goquorum-node-validator-1-0.goquorum-node-validator-1.quorum.svc.cluster.local:30303)

The format of the enodes list should be as follows.

>   enode://enode-address@faqn-or-ip-address:port-number

On the other hand, when deployed with the 'dev' helm charts, the format of enodes in the file "static-node.json" are correct, and the nodes are connect.

**Comment by joshuafernandes** [comment]
Hi @naoki4 thanks for raising this. We'll have a look and get back to you

**Comment by naoki4** [comment]
Hello @joshuafernandes.
Thank you for your action to this issue.
How is the survey situation?

**Comment by joshuafernandes** [comment]
Hi @naoki4 
We're working to simplify the charts and merging the dev and prod folders to make them easier to use - we fixed the issue and are doing our final tests this week before its released. I'll keep you posted when we do

Cheers

**Comment by libby** [comment]
Hi @naoki4, it seems related to a similar issue in AWS  https://github.com/ConsenSys/quorum-kubernetes/pull/128 if you are curious. As @joshuafernandes should be fixed in the next release.

**Comment by naoki4** [comment]
@joshuafernandes 
Thanks again.
It's good news for me.
I'll be waiting for the next release.

@libby 
Thank you for your information.
I'll check the issue.

**Comment by joshuafernandes** [comment]
Hi @naoki4 This should be sorted once #133 gets merged. Give us a yell if you run into any more issues
Cheers

**Comment by naoki4** [comment]
Hello @joshuafernandes 
I have seen PR #133 gets merged.
I'll try out the fixed templates.
Thank you.
