### ISSUE TITLE
How to automatically scall the workload to match demand?

### ISSUE THREAD

**Issue by andyafene** [ConsenSys/quorum-kubernetes#130]
Hello, 

I successfully deployed Besu.  However, "member-1" is chashing because it cannot autoscale to match demand.

Thus, I'd like to know if using the Horizontal Pod Autoscaler is the appropiate way to automatically scall the workload to match demand.

If yes, how can I implement it in this repo?

Regards,

**Comment by joshuafernandes** [comment]
Hello @andyafene this has been answered here https://discord.com/channels/905194001349627914/938504958909747250/965563388476403742

You need to enable the autoscaler on the cluster you created and isn't part of the charts in this repo. Please see the Azure docs on how to enable the autoscaler https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler
