### ISSUE TITLE
Leftovers cleanup

### ISSUE THREAD

**Issue by aliusmiles** [ConsenSys/quorum-kubernetes#137]
While poking around repo (many thanks for consolidating charts into one folder!), I've found some things which I assume to be leftovers from testing/previous manifests. My apologies if you aware about those and it's already on your todo list, but just in case:

1. curl install on startup https://github.com/ConsenSys/quorum-kubernetes/blob/b43675f5d31c865b3800a302f1b4c76f396b1911/helm/charts/goquorum-node/templates/node-statefulset.yaml#L257
curls is already installed in quorum image https://github.com/ConsenSys/quorum/blob/8bc84c7fe054db87582e2b27699d877b245fd7dd/Dockerfile#L12 plus install can fail on start if repos cache is outdated.

2. genesis.json generated by quorum-genesis-tool contains hardcoded test accounts:
```sh
      "alloc": {
        "fe3b557e8fb62b89f4916b721be55ceb828dbd73": {
          "balance": "90000000000000000000000",
          "comment": "test account from quorum-dev-quickstart -- please remove me before entering production"
        },
        "f17f52151EbEF6C7334FAD080c5704D77216b732": {
          "balance": "90000000000000000000000",
          "comment": "test account from quorum-dev-quickstart -- please remove me before entering production"
        },
        "627306090abaB3A6e1400e9345bC60c78a8BEf57": {
          "balance": "90000000000000000000000",
          "comment": "test account from quorum-dev-quickstart -- please remove me before entering production"
        },
```
I haven't found any cleanup for those, unless I've missed something. Perhaps delete them by jq or make them optional in quorum-genesis-tool?

3. helm install in quorum-k8s-hooks image https://github.com/ConsenSys/quorum-kubernetes/blob/9f77180fbc6c0b7c101065a798a0d30d9cfe5ab1/docker/quorum-k8s-hooks/Dockerfile#L13

Happy to provide PRs if needed.

**Comment by joshuafernandes** [comment]
Hi this is a good idea @aliusmiles . Could you submit a PR for this on the Quorum Genesis Tool repo please to make these optional? I'll close this issue here

**Comment by aliusmiles** [comment]
Unfortunately I'm not that familiar with js/ts to create PR for genesis tool, I was rather implying PR to this repo for curl removal or jq delete:) Though I will create an issue for that in genesis tool repo.

**Comment by joshuafernandes** [comment]
Hi @aliusmiles either works. I'll add that as a feature to the QGT and work on it when time allows, happy for you to submit a PR here though for that functionality :)

**Comment by joshuafernandes** [comment]
Hi @aliusmiles am closing this one too. PRs #141 - #145 have this all sorted now for good
