### ISSUE TITLE
quorum-k8s-hooks image optimization

### ISSUE THREAD

**Issue by aliusmiles** [ConsenSys/quorum-kubernetes#140]
Here are some items that I believe can be optimized in quorum-k8s-hooks Dockerfile, let me know if you are interested and I can provide PR for all/some of them.

1.  `mkdir -p /usr/share/man/man1; \` the issue   #https://github.com/balena-io-library/base-images/issues/273 seems to be fixed, no need for this anymore
2. `vim install` vim is not used anywhere in jobs
3. `helm install` helm is not used anywhere in jobs
4. `install quorum-genesis-tool during image build` hook jobs will run a bit faster
5. `add rm -rf /aws /awscliv2.zip to cleanup command` aws cli installation files, it will save about 200Mb from image size
6. `lock versions instead of using latest: debian image, kubectl, nodejs, azure-cli, awscli` currently every image build will produce different image with different tools versions, might lead to some unexpected behavior if there were breaking changes updates.

**Comment by aliusmiles** [comment]
Add draft PR: everything from above except 6) because not sure on best tools versions.

**Comment by joshuafernandes** [comment]
Hi @aliusmiles 

Nice work, please proceed with a PR for items 1,3,5,6 (use stable major releases where possible) 

Re 2, vim is nice to have when debugging things live and would prefer to keep that in 
Re 4, happy to lock this to a fixed version as well, now that we've got releases going it's easy to manage this.

Thanks again for looking into this!

Cheers
Josh

**Comment by aliusmiles** [comment]
Hi @joshuafernandes 

1. put vim back
2. locked qgt and kubectl versions
3. switched debian image to `stable`
4. switched nodejs version to 16.x as lts
5. removed comments since they were rather "too obvious" (this is a cat kind)
6. removed `set -eoe` and replaced `;` with `&&` so commands will still fails on error but looks a bit cleaner, imo
7. after consideration, locked only qgt version since it definitely can contain breaking changes (args/output/etc), everything else should not cause issues on update (kubectl is backward compatible few versions back after all)

Please review and let me know if any other changes are required.

**Comment by aliusmiles** [comment]
Also updated https://github.com/ConsenSys/quorum-kubernetes/pull/139 so it'll use pre-installed QGT.

**Comment by joshuafernandes** [comment]
Thank you for this @aliusmiles , have reviewed and approved. Good to merge!
