### ISSUE TITLE
Why I'm getting a "FailedScheduling" because of insufficient cpu and memory since I have enough ressources?

### ISSUE THREAD

**Issue by 0x3N3JVhPUV** [ConsenSys/quorum-kubernetes#160]
Hello,

I just deployed a new private network.
Every pods are running except  ```besu-node-member-1```.
 
Indeed, it's in "pending" state because of the following reason:
``` FailedScheduling: 0/8 nodes are available: 8 Insufficient cpu, 8 Insufficient memory ```

In order to solve this issue, I autoscaled its node pool, but no new node has been created.

Here are my settings:
I'm using a ```Standard_D4as_v5```	with the following sizes:
```4 vCPU```	and ```16 Memory: GiB```.
**Limits and requests  :**
- cpuLimit: 3
- cpuRequest: 2
- memLimit: "14G"
- memRequest: "7G"

**Autoscale nodes:**
-   min-count 6
-   max-count 71

Why am I getting a "FailedScheduling" because of insufficient cpu and memory since I have enough ressources?

**Comment by Ezzahhh** [comment]
Hello,

It is likely that AKS is not provisioning a new node despite needing a new node. This is more an AKS auto-scale problem than a problem in relation to this project. I would suggest contacting their support or filing an issue with them to follow up. I think there's no need for using auto-scaler, just scale manually when needed: https://docs.microsoft.com/en-us/azure/aks/scale-cluster?tabs=azure-cli

Note if you scale down it may drain the node so be wary of any data being lost.
