### ISSUE TITLE
permissioned-nodes.json inside k8s

### ISSUE THREAD

**Issue by kalitamih** [ConsenSys/quorum-kubernetes#162]
Good day! How does handle with permissioned-nodes.json over k8s? I am trying to connect external node to my k8s cluster by lbs and I faced with issues, that ip-address inside permissioned-nodes.json is the different from the ip-address, which is received by external node. k8s replaces this source ip-address to address K8s cluster node (this is not blockchain address).

**Comment by kalitamih** [comment]
The same inside cluster. I notice this.
```
DEBUG[09-02|19:35:36.530] isNodePermissionedV2 V2                  allowed=true  url="enode://9ff3f044040c1325008896a755ae03ff401010c4c45d13e2418734b4cc9c24dc672a604f2af1d6b7706d98a71590ded30e57a018a6286932299927b6f636c9f6@10.52.44.173:30303?discport=0"
DEBUG[09-02|19:35:36.990] isNodePermissionedV2 V2                  allowed=false url=enode://9ff3f044040c1325008896a755ae03ff401010c4c45d13e2418734b4cc9c24dc672a604f2af1d6b7706d98a71590ded30e57a018a6286932299927b6f636c9f6@10.60.5.156:38004
```
Why we see 2 different ip-addresses fro the same nodes?

**Comment by joshuafernandes** [comment]
Hello @kalitamih essentially what you need to do is find what IP your external node is running on and add that entry to the permissioned-nodes.json by hand. Restart every node in the cluster to allow this to take effect and the external node should join in if the networking is sorted (ie the nodes on the cluster can contact the external node and vice versa)

However without a diagram or environment of your setup this is near impossible to debug - can you put a diagram or something that explains your setup please?

Cheers

**Comment by joshuafernandes** [comment]
Hi @kalitamih the threads in #163 have a similar process to get things going cross cluster and might answer your question?

**Comment by kalitamih** [comment]
Hi, @joshuafernandes.
This is my setup.
`kalitamih@VivoBook-ASUSLaptop-X513EAN-K513EA:~/ptoynetwork-node$ kubectl get all
NAME                              READY   STATUS      RESTARTS      AGE
pod/blockscout-0                  1/1     Running     2 (8h ago)    33h
pod/blockscout-postgresql-0       1/1     Running     0             33h
pod/goquorum-genesis-init-6v5wm   0/1     Completed   0             3d13h
pod/goquorum-node-validator-1-0   1/1     Running     0             33h
pod/goquorum-node-validator-2-0   1/1     Running     0             33h
pod/goquorum-node-validator-3-0   1/1     Running     0             33h
pod/goquorum-node-validator-4-0   1/1     Running     10 (8h ago)   33h

NAME                                     TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                                                                       AGE
service/blockscout                       ClusterIP      10.52.38.245   <none>           4000/TCP                                                                      33h
service/blockscout-postgresql            ClusterIP      10.52.41.86    <none>           5432/TCP                                                                      33h
service/blockscout-postgresql-headless   ClusterIP      None           <none>           5432/TCP                                                                      33h
service/goquorum-node-validator-1        ClusterIP      10.52.41.134   <none>           8545/TCP,8546/TCP,8547/TCP,30303/TCP,30303/UDP,9545/TCP                       3d13h
service/goquorum-node-validator-1-lb     LoadBalancer   10.52.41.164   34.135.119.176   8545:30656/TCP,8546:30611/TCP,8547:31135/TCP,30303:32088/TCP,9545:32242/TCP   3d13h
service/goquorum-node-validator-2        ClusterIP      10.52.47.119   <none>           8545/TCP,8546/TCP,8547/TCP,30303/TCP,30303/UDP,9545/TCP                       3d13h
service/goquorum-node-validator-3        ClusterIP      10.52.44.173   <none>           8545/TCP,8546/TCP,8547/TCP,30303/TCP,30303/UDP,9545/TCP                       3d13h
service/goquorum-node-validator-4        ClusterIP      10.52.32.40    <none>           8545/TCP,8546/TCP,8547/TCP,30303/TCP,30303/UDP,9545/TCP                       3d13h
service/goquorum-node-validator-4-lb     LoadBalancer   10.52.46.187   34.122.201.161   8545:30953/TCP,8546:32728/TCP,8547:30433/TCP,30303:30758/TCP,9545:32183/TCP   3d13h

NAME                                         READY   AGE
statefulset.apps/blockscout                  1/1     33h
statefulset.apps/blockscout-postgresql       1/1     33h
statefulset.apps/goquorum-node-validator-1   1/1     3d13h
statefulset.apps/goquorum-node-validator-2   1/1     3d13h
statefulset.apps/goquorum-node-validator-3   1/1     3d13h
statefulset.apps/goquorum-node-validator-4   1/1     3d13h

NAME                              COMPLETIONS   DURATION   AGE
job.batch/goquorum-genesis-init   1/1           22s        3d13h
kalitamih@VivoBook-ASUSLaptop-X513EAN-K513EA:~/ptoynetwork-node$ `

**Comment by kalitamih** [comment]
Yes. I mean via contracts. If I don't make mistake, I can't save enode with dns name. I see enode with ip inside quourmPermission.nodeList.

**Comment by joshuafernandes** [comment]
Right, so for this you'd need to update your contracts to allow for DNS names rather than IP. We recommend using DNS names on k8s and we do this in the [static-nodes.json](https://github.com/ConsenSys/quorum-kubernetes/blob/master/playground/kubectl/quorum-go/ibft/configmap/quorum-static-nodes-configmap.yaml#L11) and local permissions too. The second reason for this is that pods are mortal and should enough go down and come up with new IP's it will actually halt your network because the permissions lists uses the older fixed IP's.

I'm not sure which contracts you are using but this is outside scope of this repo and if you need help with writing the contracts the Discord channels are the best place for that.

**Comment by kalitamih** [comment]
I use the smart contracts from https://github.com/ConsenSys/quorum-examples/tree/master/examples/7nodes/perm-contracts/v2. I have not found a newer version of these contracts yet.

**Comment by joshuafernandes** [comment]
Gotcha, I'd recommend raising a issue in that repo and linking this thread in there - from what you've described, you'll need to change the contracts to use DNS names rather than IPs; alternatively you may have to add in more IPs depending on your networking setup. Typically cross cluster comms is done via [CNI and peering VNet's](https://consensys.net/docs/goquorum/en/latest/tutorials/kubernetes/#multi-cluster) so you avoid these sorts of issues becuase of the way kubernetes networking works
