### ISSUE TITLE
Vote and exclusion of new validators hosted by another organisation: what does it require?

### ISSUE THREAD

**Issue by 0x3N3JVhPUV** [ConsenSys/quorum-kubernetes#163]
Hello,

I just deployed my Kubernetes cluster in Azure, via the ARM template (quorum-kubernetes/azure)/arm/).

Now I'd like to simulate the vote and the exclusion of new validators hosted by another organisation.

Here is what I think to do so: 
Since the "script" (quorum-kubernetes/azure)/scripts/) enables CNI to connect external nodes to my existing cluster, I guess I should create another cluster (the one who hosts the external node), peer both clusters together and make nodes and pods communicate across the clusters.

Is my reasoning correct ?

If the answear is positive:
How should I configure the external node, in order to make nodes and pods communicate across VNets?
Should pods (bootnodes and validators) of the two clusters share the same IDENTITY_CLIENTID and KEYVAULT_NAME ?

**Comment by joshuafernandes** [comment]
Hello @0x3N3JVhPUV 

That is correct, you'd peer the VNets like so https://besu.hyperledger.org/en/latest/private-networks/tutorials/kubernetes/?h=vnet#multi-cluster. Alternatively, if you are using k8s v1.24 or higher you can skip the peering and use a loadbalancer with a fixed ip to connect all peers to the external node.

Everything on one cluster is completely seperate to everything on the other cluster (identity, keyvault, RBAC's etc) - the only thing that you are doing is peering them to join the network so to speak. 

Once that is setup, you need to point the external node to the bootnodes or peers of the main cluster and open up 30303 for the nodes to connect. If you are using static-nodes or the like you need to edit these by hand to add in the external node.

**Comment by 0x3N3JVhPUV** [comment]
Thank you @joshuafernandes,

So, should I just run the helm commands for bootnodes and validators in my second cluster? Or should run all helm commands included the genesis?
In the first cluster I setup 4 validators in the genesis and 4 validators are already running on it. Is that mean that I should add one more validator in the genesis in order to have an external validator?
Regards,

**Comment by joshuafernandes** [comment]
Hi @0x3N3JVhPUV 
So slightly more involved. Basically on a new cluster if the genesis etc is rerun you will get a different network - all nodes on the same network need the same genesis file. So what you'd do is let say you start with the original cluster (`cluster A`) and the external one on (`cluster_B`)

I believe you have cluster_A already sorted, so:

**Comment by joshuafernandes** [comment]
If you are peering the Vnets instead, do that after you spin up the `cluster_B`  and leave the enode as is in the steps later down (ie you don't need a load balancer here as you've peered the Vnet so connectivity between clusters is established). Also ignore the step re network security group rules as that will be set at the VNet level when you peer

**Comment by 0x3N3JVhPUV** [comment]
Thank you @joshuafernandes for your prompt answer!

Yes I'm peering the Vnets. 

I spined up the cluster_B, I create its namespace but couldn't find the static-nodes.json in the "quorum-kubernetes" repository.
I could only find it on the Azure portale, here:
![image](https://user-images.githubusercontent.com/46408093/188642182-2905a80d-c158-44bd-9d6a-19b1ad0af977.png)

Now, when I'm trying to copy/past it (with the Azure portale) from cluster_A to cluster_B, I have the following message:
![image](https://user-images.githubusercontent.com/46408093/188643147-435feef4-b8e9-45c0-b2bf-186563995110.png)
Same thing with the genesis...

So I guess I should copy/past them (genesis and the static-nodes.json) on the repository (quorum-kubernetes). 
I can easly imagine where to past the genesis but where am I supposed to past the static-nodes.json, since it will be used to run the chart, to create my new node?
And how am I going to run it with the helm chart?

I also notice that the genesis on cluster_A ( in the Azure portale) is different that the one (on chart/besu-genesis/value.yaml) I'm using to deploy it.
Here is an example:
![alloc](https://user-images.githubusercontent.com/46408093/188649369-0b6925ae-b515-4f23-bddd-126eb0dc2804.PNG)
![alloc2](https://user-images.githubusercontent.com/46408093/188649458-dac84b97-4a5b-439a-b2a9-5723c8af45e2.PNG)
Why such a difference?

Regards,


Regards,

**Comment by 0x3N3JVhPUV** [comment]
Thank you @joshuafernandes for your prompt answer!

Yes, I'm peering the Vnets. 

Thus, I spun up the `cluster_B,` I created its namespace, but couldn't find the `static-nodes.json` in the `quorum-kubernetes"` repository. 

So, in Azure portale, I tried to copy/past the content of the `besu-peers` file (in Home/Ressource_groupe/cluster_A/configuration) from cluster_A to cluster_B, but I got the following error message:
![image](https://user-images.githubusercontent.com/46408093/188688914-3a4080d9-680c-488c-9791-c47bbd5f7358.png)
Same thing with the genesis...
**Note: the `besu-peers` data = the content of `static-nodes.json`.**

Therefore, I copy the content of the `besu-peers` file (in Home/Ressource_groupe/cluster_A/configuration) and pasted it in `charts/besu-node/values.yaml` in my `quorum-kubernetes` repository.
Here is a screenshot where I changed the path of the `static-nodes` by the content of `besu-peers`.
![image](https://user-images.githubusercontent.com/46408093/188696396-79f62c92-cee5-4a3c-aa97-e8dd08e97b5b.png)

The reason why I did it, it's because I couldn't find , the `static-nodes` in the the `quorum-kubernetes` repository.
Then I ran the chart to create my new node on `cluster_B` with the same repository with which I deployed cluster_B, excepeted the fact that I change the `static-nodes` option in `charts/besu-node/values.yaml`.
To do so, I ran all the helm commands and created just one validator that I named validator-5.

I dont no yet if I'm doing good because both bootnodes and validator_5 are pending because of a `FailedScheduling`, but I'd like to know if I have the good approach yet. 

Regards,

**Comment by joshuafernandes** [comment]
Hi @0x3N3JVhPUV the peer lists are created via the genesis chart, and then are updated on the fly when new nodes enter/leave the cluster. The configmaps may be called besu-peers/goquorum-peers and inside them is the content of the static-nodes.json that gets mounted. 

Essentially in `cluster_B` you need to manually copy and paste everything that the genesis chart would have created, ie genesis file, static-nodes (or peers for besu) and keep the names the same. Have a look at the genesis chart [templates](https://github.com/ConsenSys/quorum-kubernetes/blob/master/helm/charts/besu-genesis/templates/genesis-job-init.yaml#L93) and the[ pre-install hooks ](https://github.com/ConsenSys/quorum-kubernetes/blob/master/helm/charts/besu-node/templates/node-hooks-pre-install.yaml#L43) in the besu-node chart so you can see what's happening there. `p2p.staticNodes` expects a file path not a list of nodes so that will not work.

Rather than this approach, I'd suggest using the [playground examples](https://github.com/ConsenSys/quorum-kubernetes/tree/master/playground/kubectl/quorum-besu) where there is less automation and things are more static so you can see the individual pieces and what's going on. Note that you only need one of bootnodes or static-nodes.json; you can have both but it isn't required - the playground examples uses bootnodes and permissions. Use the playground examples to get what you want working cross cluster and the move to using the charts. What you are attempting to do is reasonably involved, and you will likely need to customise things to get it working for your setup so doing the playground examples first will help you understand what the moving pieces are.

**Comment by 0x3N3JVhPUV** [comment]
Hi @joshuafernandes,

Thank you for your answer!

I finally could copy/past the genesis and the `static-nodes` from `cluster_A` to `clusterB.`

The reason why I was getting an `error 500` was that `ressourceVision` should not be set on objects to be created. 
So, I removed it from both files ( genesis and the static-nodes) before pasting them on `cluster_B.`

Then, I ran the chart to create my new node on `cluster_B` and add the node's enode to the `static-nodes.json` on `cluster_A.`

However, when comparing the before and the after of the creation of my external node, the number of peers remain the same....

Here is the command I'm using to get the number of peers:
`curl -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":53}' http://xxxxxxxxx/rpc`

What did I miss?

That said, I forgot to mention that, I want in my simulation `cluster_A` to be `permissioned.`
So, I guess, I should enable the nodes `allowlist`. 
right?

If "yes", what else should I do in this scenario?

Can you, please, tell me what are the steps to follow with a permissioned cluster_A?

Last, I noticed that the genesis.json generated by my `chart/besu-genesis/values.yaml` contains hardcoded test accounts:
```
      "alloc": {
        "fe3b557e8fb62b89f4916b721be55ceb828dbd73": {
          "balance": "90000000000000000000000",
          "comment": "test account from quorum-dev-quickstart -- please remove me before entering production"
        },
        "f17f52151EbEF6C7334FAD080c5704D77216b732": {
          "balance": "90000000000000000000000",
          "comment": "test account from quorum-dev-quickstart -- please remove me before entering production"
        },
        "627306090abaB3A6e1400e9345bC60c78a8BEf57": {
          "balance": "90000000000000000000000",
          "comment": "test account from quorum-dev-quickstart -- please remove me before entering production"
        },
```

Why am I getting those test accounts, since I didn't add them in my `chart/besu-genesis/values.yaml`?

Here is a screenshot of my genesis:
![alloc](https://user-images.githubusercontent.com/46408093/189036188-4690d37a-9229-41f3-b029-daff14273734.PNG)


Regards,

**Comment by joshuafernandes** [comment]
Hi @0x3N3JVhPUV I'd strongly suggest you look at the playground setup and start afresh. Once you undestand how all that works ie (genesis, accounts, permissions, static-nodes & cross cluster) then move to the helm charts. You've got quite a few issues and attempting to add functionality while fixing them all at once isn't ideal. Going through things one at a time is a better approach to understanding how this works,

In the playground setup, you control everything to the last detail and you can see what happens. In the prod setup we use the [QGT](https://github.com/ConsenSys/quorum-genesis-tool) to create the genesis artifacts, and there is an option to turn the test accounts off. They're on by default because most users run them and then don't have any accounts setup ie they therefore cannot make any txns. 

Re the peer counts you can check what peers are missing with https://besu.hyperledger.org/en/latest/public-networks/reference/api/#admin_peers and check logs would be the best place to see what happened.

Have you tried permissioning with something like the dev quickstart or equivalent locally? https://besu.hyperledger.org/en/latest/private-networks/concepts/permissioning/ Of the two types local permissioning is easier and we have a tutorial here https://besu.hyperledger.org/en/latest/private-networks/tutorials/permissioning/. Once you have this working locally, its pretty much the same setup on k8s

**Comment by 0x3N3JVhPUV** [comment]
Hi @joshuafernandes,

Thank you for your clear and prompt answer!

I'll definitaly look at the playground.

Yes, I already tried this tutorial ( https://besu.hyperledger.org/en/latest/private-networks/tutorials/permissioning/).

I'll try it again and I'll be back with feedbacks.

Regards,

**Comment by joshuafernandes** [comment]
:+1:

**Comment by 0x3N3JVhPUV** [comment]
Hi @joshuafernandes,

I didn't finish yet look at the playground, but I have a question regarding my previous issue.
 
In `chart/besu-genesis/values.yaml`, shouldn't I need, as part of my authorized network configuration, a file path to authorize access to the specified nodes?

If the answer positive; what's the path and why is it empty?
If the answer is negative; how am I supposed to whitliste specified nodes without it?

Regards,

**Comment by joshuafernandes** [comment]
Hi @0x3N3JVhPUV,

I'd suggest starting with the tutorials here https://besu.hyperledger.org/en/latest/private-networks/tutorials/permissioning/ and pick the method of permissions you want to use ( local permissions is the preferred choice and then move to contracts if required).

If you need a setup that works already use the Quorum Dev Quickstart which has examples of static nodes and local permissions. 

The genesis file on a private chain (&chart here) has nothing to do with permissions - it merely sets out the first block for the network; who the validators are and any beneficiary accounts. 

I'd strongly suggest going through the tutorials first, move to the quorum dev quickstart and then the k8s playground piece. These are concepts not really related to this repo so I'd also recommend posting in the official discord channels https://discord.com/channels/905194001349627914/938504958909747250 and https://discord.com/channels/697535391594446898/743193040197386451

I really wouldn't suggest attempting to learn permissioning in a k8s environment for the first time, as there are a lot of moving pieces

Regards

**Comment by 0x3N3JVhPUV** [comment]
Hi @joshuafernandes,

Thank you for your answer.
You are completely right about the fact that The genesis file on a private chain has nothing to do with permissions. I just pasted the wrong path. I'd past this one `chart/besu-genesis/values.yaml`. Sorry about that.
That said, I'll definitaly go through the tutorials and the quorum dev quickstart before the k8s playground piece.

Regards,

**Comment by 0x3N3JVhPUV** [comment]
Hi @joshuafernandes,

From my understanding of this [turorial](https://besu.hyperledger.org/en/latest/private-networks/tutorials/permissioning/), I need private network PERM (permissioning) methods, such as `perm_addNodesToAllowlist`, for local permissioning. 

In the "quorum-kubernetes" k8s environment, It seems that I have to do two things ( in `chart/besu-node/values.yaml`), in order to be able to use those methods:

1. Setting `permissions.node.enable` to `true`.
2. Adding the right value to the `permissions.filepath` (which is empty by default).

If I skip the first step, I'm getting the following ouptut:
```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"perm_getNodesAllowlist","params":[], "id":1}' http://xx.xx.xxx.xxx/rpc
{
  "jsonrpc" : "2.0",
  "id" : 1,
  "error" : {
    "code" : -32000,
    "message" : "Node allowlist has not been enabled"
  }
}
```
And If I just do the first step, pods are crashing because of the empty value of `permissions.filepath`:
```
besu-genesis-init-2snh7                                           0/1     Completed          0               21h
besu-node-bootnode-1-0                                            0/1     CrashLoopBackOff   6 (4m32s ago)   10m
besu-node-bootnode-2-0                                            0/1     CrashLoopBackOff   6 (4m21s ago)   10m
besu-node-member-1-0                                              1/2     CrashLoopBackOff   6 (112s ago)    7m44s
besu-node-rpc-1-pre-install-hook-h2nnh                            0/1     Completed          0               11m
besu-node-validator-1-0                                           0/1     CrashLoopBackOff   6 (4m9s ago)    10m
besu-node-validator-2-0                                           0/1     CrashLoopBackOff   6 (4m3s ago)    9m44s
besu-node-validator-3-0                                           0/1     CrashLoopBackOff   6 (3m25s ago)   9m21s
besu-node-validator-4-0                                           0/1     CrashLoopBackOff   6 (2m15s ago)   8m15s
```
```
my-prompt:~/besu-prod2/helm$ kubectl logs besu-node-validator-2-0 --namespace quorum
Defaulted container "validator-2-besu" out of: validator-2-besu, volume-permission-besu (init)
Setting logging level to ERROR
Unable to read permissioning TOML config file :  Configuration file does not exist: 

To display full help:
besu [COMMAND] --help
```
Thus, in this context, is it correct to think that getting the missing value of `permissions.filepath` seems to be the solution to be able to use the PERM (permissioning) methods ?

If the answer is positivie, can you shed some light on how to do it, because after many tries and even based on pertinent [tutorial](https://rafal-wawrzyniak.medium.com/private-hyperledger-besu-network-part-3-permissions-not-everyone-is-welcomed-here-75f88baf31fa), I could not get the right value for `permissions.filepath`.

Or is there something that I missed in my understanding of how permissioning locally works (in the "quorum-kubernetes" k8s environment) ?
