### ISSUE TITLE
Elixir Error in consensys/blockscout:v4.1.5-beta

### ISSUE THREAD

**Issue by MaximilianIML** [ConsenSys/quorum-kubernetes#170]
Hello everyone.
I successfully added `consensys/blockscout:v4.0.0-beta`-Image to my GoQuorum network on Openshift cluster.

Unfortunatelly Blockscout is not able to index a transaction. Instead I got an error with the following message:
`    {:unknown_key, %{key: "isPrivacyMarkerTransaction", value: false}}`
This problem is already discribed in https://github.com/blockscout/blockscout/issues/4995.

So I tried the same tutorial (https://consensys.net/docs/goquorum/en/latest/tutorials/kubernetes/deploy-charts/#9-blockchain-explorer) with the newer image `consensys/blockscout:v4.1.5-beta`.
But now I run in an Elixir error:

```
** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Repo
    ** (EXIT) an exception was raised:
        ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Indexer.BoundQueue, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
            (elixir 1.13.1) lib/enum.ex:1: Enumerable.impl_for!/1
            (elixir 1.13.1) lib/enum.ex:143: Enumerable.reduce/3
            (elixir 1.13.1) lib/enum.ex:4144: Enum.reverse/1
            (elixir 1.13.1) lib/keyword.ex:186: Keyword.new/2
            (explorer 0.0.1) lib/explorer/repo/config_helper.ex:34: Explorer.Repo.ConfigHelper.extract_parameters/1
            (explorer 0.0.1) lib/explorer/repo/config_helper.ex:25: Explorer.Repo.ConfigHelper.get_db_config/1
            (explorer 0.0.1) lib/explorer/repo.ex:20: Explorer.Repo.init/2
            (ecto 3.7.1) lib/ecto/repo/supervisor.ex:25: Ecto.Repo.Supervisor.runtime_config/4
```

Do you have any idea how I could solve one these issues?
I do not care, if I use 4.0.0 or 4.1.5, I just want Blockscout to show transactions.

**Comment by joshuafernandes** [comment]
Hi @MaximilianIML, thankyou for raising this. Unfortunately, this is something we don't provide support for and recommend you raise this on the Blockscout issues page here: https://github.com/blockscout/blockscout/issues

**Comment by MaximilianIML** [comment]
@nicwhitts No, unfortunately the problem persists.

**Comment by nicwhitts** [comment]
I downgraded to 4.0.0 and it got me a working build. But I didn’t have your other error

**Comment by nicwhitts** [comment]
Actually i do have the same error!
