### ISSUE TITLE
Balance issue with genesis file

### ISSUE THREAD

**Issue by soragXYZ** [ConsenSys/quorum-kubernetes#176]
Hi!

For some reason, my network is not the same as my genesis file specifies. More specifically, I have an issue with the initial balances.

My parameter "alloc" is not taken into account, all addresses have 0 balance

Is there a parameter that I missed ?

Thanks

**Comment by 0x3N3JVhPUV** [comment]
I'm facing the same issue.
Indeed, the genesis.json, which is generated by chart/besu-genesis/values.yaml, contains hardcoded test accounts:
```
      "alloc": {
        "fe3b557e8fb62b89f4916b721be55ceb828dbd73": {
          "balance": "90000000000000000000000",
          "comment": "test account from quorum-dev-quickstart -- please remove me before entering production"
        },
        "f17f52151EbEF6C7334FAD080c5704D77216b732": {
          "balance": "90000000000000000000000",
          "comment": "test account from quorum-dev-quickstart -- please remove me before entering production"
        },
        "627306090abaB3A6e1400e9345bC60c78a8BEf57": {
          "balance": "90000000000000000000000",
          "comment": "test account from quorum-dev-quickstart -- please remove me before entering production"
        },
```
Even after turning the test accounts off, I still have the hardcoded test accounts.
Why am I getting those test accounts, since I didn't add them in my chart/besu-genesis/values.yaml and turning the test accounts off? And where can I find the private keys?

Regards,

**Comment by anuj-upadhyay-inferenz** [comment]
@0x3N3JVhPUV change the image tag to qgt-0.2.3 at the end.

**Comment by joshuafernandes** [comment]
Hello @soragXYZ this has been sorted in 0.2.3 of the QGT, not sure what version you were using when you ran this?

**Comment by soragXYZ** [comment]
Hi again @joshuafernandes 

I'm actually using the 0.2.3 QGT version, and I still have the issue. I'm trying to pre fund account using the genesis file (https://besu.hyperledger.org/en/stable/private-networks/how-to/configure/contracts/)

I'm using the K8's version on Azure

In fact some parameters seem to be ignored during the configuration. For example, I want to use one of the latest milestone for my private network (grayGlacier), but the created genesis.json uses the constantinople milestone ( + the issue with alloc and accounts not pre funded)
