### ISSUE TITLE
Enable possibility to have p2p discovery (UDP) on a custom port number, different from p2p sync port (TCP, 30303)

### ISSUE THREAD

**Issue by skatrych** [ConsenSys/quorum-kubernetes#183]
# Problem
When deploying Besu network to AWS + EKS, we do expose p2p ports to outside of the cluster to enable communication with external nodes that are deployed elsewhere in the world. We do that via AWS Load Balancer. However, it does not work to configure load balancer to support UDP and TCP on the same port number (30303) at the same time. 

Current implementation of the helm chart is enforcing to use same port number for both: 
- p2p communication between nodes (TCP)
- p2p discovery (UDP)

# Proposal
Make helm chart implementation flexible to allow responsible engineers to configure different port number for Discovery (UDP).

**Comment by joshuafernandes** [comment]
Hello @skatrych This is a limitation with AWS EKS and has been a long standing issue that they are aware of. As per the spec from 1.24 this was supposed to be possible but this hasn't been implemented by them. This is a request for the both clients (besu & goquorum), when they make that possible we can add that functionality here. Please raise this in the hyperledger/besu & goquorum issues pages
