### ISSUE TITLE
How do I use the raft consensus algorithm？

### ISSUE THREAD

**Issue by 13310241314** [ConsenSys/quorum-kubernetes#189]
hello everyone：
When I set rawGenesisConfig.genesis.config.algorithm.condensus in "help/charts/goquorum-generesis/values.yaml" and "helm/values/genesis-goquorum.yml" to raft.
And when I start goquorum in k8s according to the following method in helm:
https://github.com/ConsenSys/quorum-kubernetes/tree/master/helm#for-goquorum

All pods of validator nodes report the following error:
 Fatal: Consensus not specified. Exiting!!

![image](https://user-images.githubusercontent.com/125418632/218900038-b53b0bf3-f5bc-40a7-bb2d-ffef0bc827f2.png)

But everything works normally when rawGenesisConfig.genesis.config.algorithm.condensus is set to qbft ibft or clique.

Please help me. Thank you very much.

**Comment by joshuafernandes** [comment]
Hello @13310241314 

Raft isn't supported for production and so hasn't been supported in this repo. Please use one of the other algorithms ie QBFT, IBFT2 or IBFT

Cheers

**Comment by 13310241314** [comment]
OK. Thanks very much for talking to me

**Comment by 13310241314** [comment]
> Hello @13310241314
> 
> Raft isn't supported for production and so hasn't been supported in this repo. Please use one of the other algorithms ie QBFT, IBFT2 or IBFT
> 
> Cheers

OK. Thanks very much for talking to me.
