### ISSUE TITLE
InternalServerError at the deployment with azuredeploy.json

### ISSUE THREAD

**Issue by naoki4** [Consensys/quorum-kubernetes#191]
Hello everyone.

When I deploy with the template "azure/arm/azuredeploy.json",
all of "microsoft.insights/metricAlerts" resources are not created by InternalServerError.
The status mesage in the Operation details pane is as follows:

{
    "status": "Failed",
    "error": {
        "code": "Add or Update Resourcetype microsoft.containerservice__managedclusters__device__host__Microsoft.ResourceId in MdmAcount: CUSTOMMETRIC_2dbc4fe3-6578-46fc-8823-4d9a5dd5a80f_JapanEast failed",
        "message": "There was a problem with the server. Please try again in a few minutes. Activity ID: 5e33eab3-d813-40ee-9026-b01aa379185c."
    }
}

By deleting all "microsoft.insights/metricAlerts" type from azuredeploy.json, the deployment is successful.

How can I deploy with the original ARM template?

![20230317T175350](https://user-images.githubusercontent.com/86452250/225860217-d28339c0-bff3-419f-9240-da578f80f389.png)

**Comment by naoki4** [comment]
For the time being, I would like to set these metric alerts manually.
If someone find the way to correct the internal server errors, please let me know.

**Comment by joshuafernandes** [comment]
Hello @naoki4 

Im out of office at the moment, so cannot check what the response from MSFT is when deployed. In the `azuredeploy.json` you are free to customize to suit your reqs so you can pull them out and set the alerts manually. I'll have a look at the deploy when Im back and post an update - it's likely a version update that'll need to be done

Cheers
Josh

**Comment by joshuafernandes** [comment]
Hello @naoki4 This should be sorted, the only thing I had to update in the template was the aks version. Can confirm the current template works fine

![image](https://github.com/Consensys/quorum-kubernetes/assets/3722503/70a56201-6374-4abf-804d-4b865ea33d17)
