### ISSUE TITLE
Is this helm chart rpc node do load balancing to other nodes?

### ISSUE THREAD

**Issue by nowjean** [ConsenSys/quorum-kubernetes#192]
I have installed besu cluster on AKS through this helm chart.
There are rpc, member, boot, validator nodes. I wondering about rpc node's load balancing.
Does RPC node do load balancing request to other nodes?

Or, do i have to configure load balancer manually like below description?
https://besu.hyperledger.org/en/latest/public-networks/how-to/configure-ha/sample-configuration/#elastic-kubernetes-service

Thanks.

**Comment by joshuafernandes** [comment]
Hi @nowjean 

We typically tend to use the ingress to load balance similar to the linked page but slight mod - we make a generic service that targets n statefulsets and the ingress in front, reason being if one goes weird we can just pull that one out and service is not interrupted, whereas with increasing replicas the odds of an issue being carried across all replicas is higher.

I imagine you could increase the replicas and use a load balancer for the service (but we haven't attempted this ourselves) Either should work for you once tested for your needs

Cheers
Josh
