### ISSUE TITLE
How do I stop a Quorum node?

### ISSUE THREAD

**Issue by ivis-minoue** [ConsenSys/quorum-kubernetes#194]
I have a question about a Quorum node built using Quorum-Kubernetes.
How do I stop a Quorum node?
When updating an existing network with new blockperiodseconds, the Quorum node must be stopped.

**Comment by joshuafernandes** [comment]
Hi @ivis-minoue 

To stop a node you delete the chart, and set the override values to retain the keys. Data will be preserved on a pvc (assuming cloud of choice)

Upgrade the genesis 

Install the chart and it'll pick up from where it started.

An easier alternative to this is to update the genesis in the configmap as is and then update the node as normal when you do a version update etc

**Comment by ivis-minoue** [comment]
Thank you for your reply.

I understand that I can update the genesis by the operation that
 - delete the chart with the command like "helm uninstall validator-1 --namespace quorum"
 - set the override values to retain the keys (*1)
 - upgrade the genesis
 - install the chart with the command like "helm install validator-1 ./charts/goquorum-node --namespace quorum --values ./values/validator.yml"

Also, I understand there is another easier operation to update the genesis that I update the genesis in the configmap and update the node (*2).

I have two questions.

(1) Could you tell me the operations in detail about "set the override values to retain the keys (*1)"?
I think it means I should edit a file in the "quorum-kubernetes/helm/values/" folder so that the newly installed pods use the same keys the deleted pods used, but I don't know which file should be edited and which values should be overridden.

(2) Is the following command correct to "update the node (*2)"?
  helm upgrade validator-1 ./charts/goquorum-node --namespace quorum --values ./values/validator.yml
  (the validator-1 node for example)
