### ISSUE TITLE
Error on node-statefulset.yaml when running helm install validator

### ISSUE THREAD

**Issue by heryanto87** [Consensys/quorum-kubernetes#206]
Error Message: "Error: INSTALLATION FAILED: parse error at (besu-node/templates/node-statefulset.yaml:334): unexpected EOF"
terminal: "helm install validator-1 ./charts/besu-node --namespace besu --values ./values/validator.yml"

how to reproduce:
i followed https://www.zeeve.io/blog/how-to-deploy-a-hyperledger-besu-network-on-kubernetes/ tutorial to deploy private blockchain using quorum-kubernetes.

can anyone also reproduce this error?

**Comment by iv7dev** [comment]
me too. same error, i use helm lint but nothing for now.

**Comment by joshuafernandes** [comment]
@heryanto87 Can you please provide steps to reproduce this?

- What is your environment?
- Are you running local on minikube/equivalent - cloud etc?
- What algorithm are you using and what changes if any have you made to the charts?
