### ISSUE TITLE
Migration Plan from kubernetes.io/azure-file to file.csi.azure.com in Azure AKS v1.26 and Compatibility with Kubernetes v1.27

### ISSUE THREAD

**Issue by YosukeAbe47** [Consensys/quorum-kubernetes#219]
I am currently operating quorum-kubernetes using Azure's AKS version 1.26. With the transition to Kubernetes version 1.26, kubernetes.io/azure-file has become deprecated, yet it is still being used in the following section:
https://github.com/Consensys/quorum-kubernetes/blob/master/helm/charts/goquorum-node/templates/node-storage.yaml#L10C2-L10C2

Is there any plan to address this? While it seems that Azure has no plans yet to remove the driver, would it be alright to migrate from kubernetes.io/azure-file to file.csi.azure.com? In that case, I am considering changing the provisioner and proceeding with the migration as described in Azure's documentation here:
https://learn.microsoft.com/en-US/azure/aks/csi-migrate-in-tree-volumes#create-a-dynamic-volume
Also, would there be any issue in updating Kubernetes to version 1.27 afterwards?

**Comment by nowjean** [comment]
@YosukeAbe47  Please view my PR. #226 

I have customized and used my own azue file storageClass for private storage account.
So, I didn't realize this issue. After merge these PR: #225 #226, This Helm chart working correctly in AKS 1.27!  
If you want use this chart before merge above PRs,  you can edit your chart first.

Thanks for sharing!

**Comment by YosukeAbe47** [comment]
Thanks for your support!
