### ISSUE TITLE
Cannot deploy contract with zero gas

### ISSUE THREAD

**Issue by HairyMike** [Consensys/quorum-kubernetes#220]
I've deployed a besu network using helm to azure.

After deploying the network, I attempted to deploy a zero gas contract to it and noticed that it was being rejected with the message: `Gas price below configured minimum gas price`

I referred to the guide here for how to configure zero gas price: https://besu.hyperledger.org/23.4.0/private-networks/how-to/configure/free-gas
specifically:
1. Changed gas limit to `0x1fffffffffffff` here -> https://github.com/Consensys/quorum-kubernetes/blob/master/helm/values/genesis-besu.yml#L36
2. I see there is no option for contractSizeLimit in the `quorum-genesis-tool`, so I ran the genesis chart then made a manual edit to the `genesis` config map (before running any other charts).
3. `--min-gas-price=0` is already being applied in the cmd line options here: https://github.com/Consensys/quorum-kubernetes/blob/master/helm/charts/besu-node/templates/node-statefulset.yaml#L279 although I can see in the logs that it is being ignored because the nodes are not miners (I also tried enabling mining and nominating a rewards address - through args to the besu cli).
4. I could see the London fork config for zero gas was already in the genesis file.

I can get the contract to deploy, and call methods on it when I use a gas fee of 8 gwei.

One other piece of information, I can query each node (pod) with an rpc call to get the gas price.  Each node is replying with gas price `0x0`.

Any ideas what I could be missing?

**Comment by refl3ction** [comment]
This Chart uses besu version `22.7.2`, it took me a long time to realize that was why the zero gas configuration was not working. It worked after I updated it to `23.10.0`.

**Comment by HairyMike** [comment]
I did get this working as well.  Updating to latest besu version helped, and I also added the following to the genesis config:
```
baseFeePerGas: "0x0"
nonce: "0x0"
```

**Comment by smatthewenglish** [comment]
yeah, i also am having this problem. 

```
➜  besu git:(main) ✗ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":53}' http://localhost:8545 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   117    0    56  100    61    669    728 --:--:-- --:--:-- --:--:--  1409
{
  "jsonrpc": "2.0",
  "id": 53,
  "result": "0x0"
}
```

^the gas price shows as zero but i can't deploy a contract for anything less than 7 wei. 

@HairyMike & @refl3ction you're saying if i update the besu version it'll work?

**Comment by HairyMike** [comment]
@smatthewenglish if you update the besu version and make sure those properties are in the genesis configmap before you bring up the network.  The cli tool can't set these for you AFAIK - I manually edit the configmap.

There are also some breaking changes in the args to the besu CLI.  We had to change some of the args to the besu cli (breaking changes).

**Comment by smatthewenglish** [comment]
> @smatthewenglish if you update the besu version and make sure those properties are in the genesis configmap before you bring up the network. The cli tool can't set these for you AFAIK - I manually edit the configmap.
> 
> There are also some breaking changes in the args to the besu CLI.

amazing, thank you! <3

you wouldn't happen to have a branch with those changes applied would you?

why do you have to set nonce to zero?

**Comment by HairyMike** [comment]
_you wouldn't happen to have a branch with those changes applied would you?_
one of my colleagues is planning to make a PR to upgrade the version of besu - coming soon :)

_why do you have to set nonce to zero?_
I read a whole series of github issues and articles, and this was suggested by a commenter (apologies don't have a link at hand)

**Comment by HairyMike** [comment]
https://github.com/Consensys/quorum-kubernetes/pull/234

**Comment by smatthewenglish** [comment]
to update it you need to remove these values

<img width="1442" alt="Screenshot 2024-05-22 at 1 27 40 PM" src="https://github.com/Consensys/quorum-kubernetes/assets/9053984/a8f53f2a-d6ff-412e-8502-c29ada4e6888">

which seems to break it

**Comment by HairyMike** [comment]
@smatthewenglish this change is on master now (see the PR)

**Comment by HairyMike** [comment]
I believe we still need the baseFeePerGas setting in the genesis config which is why I haven’t closed this issue.

**Comment by smatthewenglish** [comment]
hell yeah! nice 🙌 ty
