### ISSUE TITLE
not able to deploy template

### ISSUE THREAD

**Issue by pranjali301** [Consensys/quorum-kubernetes#229]
can anyone help me , i upadate the vpc details and now i am facing some errors like this Error: loading config file "./cluster.yml": error unmarshaling JSON: while decoding JSON: json: unknown field "subnets"

**Comment by joshuafernandes** [comment]
Hello @pranjali301 did you update the cluster.yml with details of your VPC? Step 1 of the [usage details](https://github.com/Consensys/quorum-kubernetes/tree/master/aws#usage)

**Comment by pranjali301** [comment]
yes i did, only node group stack failed.i didn't get the solution, pls help if possible

**Comment by joshuafernandes** [comment]
Unsure of this one @pranjali301 . Am unable to reproduce this issue so cannot provide assistance. That being said AWS has several examples of using EKS to spin up a cluster and all you need is a cluster and the rest should work
