### ISSUE TITLE
Unable to deploy from documentation due to mixed namespaces

### ISSUE THREAD

**Issue by EPinci** [Consensys/quorum-kubernetes#235]
Hello,

I'm trying to deploy to kubernetes according to this documentation:
https://besu.hyperledger.org/private-networks/tutorials/kubernetes/charts
but the deployment fails due to mixed namespaces in the commands.

Initial step guides you to create a `besu` namespace but some of the commands (and some of the manifests like the ones on `/helm/values/monitoring/*` are hardcoded to a `quorum` namespace.
Are all of the instances of `quorum` supposed to be replaced with `besu`?

Thank you.

**Comment by joshuafernandes** [comment]
Hello @EPinci

The namespaces need to be set per how you want to deploy - we suggest  a `monitoring` namespace for the monitoring components - it has a clusterrole so it can fetch metrics from any namespace.
