### ISSUE TITLE
Pod Stuck in ContainerCreating State Due to Missing ConfigMaps

### ISSUE THREAD

**Issue by Params10** [Consensys/quorum-kubernetes#240]
The Kubernetes pod besu-node-validator-1-0 is stuck in the ContainerCreating state because it is unable to find the required ConfigMaps besu-peers and besu-genesis. This prevents the pod from mounting the necessary volumes and proceeding to the Running state.
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    2m30s                default-scheduler  Successfully assigned quorum/besu-node-bootnode-1-0 to gke-cluster-1-brl-pool-1-feaf5af2-xwgb
  Warning  FailedMount  22s (x9 over 2m30s)  kubelet            MountVolume.SetUp failed for volume "static-nodes" : configmap "besu-peers" not found
  Warning  FailedMount  22s (x9 over 2m30s)  kubelet            MountVolume.SetUp failed for volume "genesis" : configmap "besu-genesis" not found
  
  Cloud- Googlecloud
  Only changes done from current master are :\

1. **kept local instead of aws/azure**

2.gke config added to yamls
gke:
  serviceAccountName:   # The name of the GKE service account to use
  nodePoolName:Specify the GKE node pool if needed
  region:  # Specify the region for GKE
  projectID:   # The GCP project ID where GKE is deployed
  
3.  sh script used to deploy:

#GKE
helm repo add elastic https://helm.elastic.co
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
cd charts
helm install blockscout ./blockscout --namespace quorum --create-namespace --values ./blockscout/values.yaml
helm repo update
cd ..
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm install monitoring prometheus-community/kube-prometheus-stack --version 34.10.0 --namespace=quorum --create-namespace --values ./values/monitoring.yml --wait
kubectl --namespace quorum apply -f  ./values/monitoring/
helm install genesis ./charts/besu-genesis --namespace quorum --create-namespace --values ./values/genesis-besu.yml
helm install bootnode-1 ./charts/besu-node --namespace quorum --values ./values/bootnode.yml
helm install validator-1 ./charts/besu-node --namespace quorum --values ./values/validator.yml
helm install validator-2 ./charts/besu-node --namespace quorum --values ./values/validator.yml
helm install member-1 ./charts/besu-node --namespace quorum --values ./values/txnode.yml
helm install rpc-1 ./charts/besu-node --namespace quorum --values ./values/reader.yml
helm install quorum-monitoring-ingress ingress-nginx/ingress-nginx \
    --namespace quorum \
    --set controller.ingressClassResource.name="monitoring-nginx" \
    --set controller.ingressClassResource.controllerValue="k8s.io/monitoring-ingress-nginx" \
    --set controller.replicaCount=1 \
    --set controller.nodeSelector."kubernetes\.io/os"=linux \
    --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.admissionWebhooks.patch.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.service.externalTrafficPolicy=Local
kubectl apply -f ../ingress/ingress-rules-besu.yml

**Comment by cdivitotawela** [comment]
I have checked this in minikube. While I am not exactly sure the cause of the issue but my best guess is that you might have executed the subsequent commands immediately after the `helm install genesis ./charts/besu-genesis --namespace quorum --create-namespace --values ./values/genesis-besu.yml`

Running chart `besu-genesis` creates the required config maps. It takes few minutes to create these config maps `besu-genesis` and `besu-peers`. These config maps then mounted on to nodes. Based on the error it seems these config maps are missing.

1. Check config maps available in `quorum` namespace with command `kubectl -n quorum get cm`
2. Check the logs of the pod with name similar to `besu-genesis-init-nxflw`. Command to run `kubectl -n quorum logs besu-genesis-init-xxxxxxx`. Output will be as below where it indicate it creating these config maps.

```
Creating config ...
Creating bootnodes configmap in k8s ...
error: failed to create configmap: configmaps "besu-bootnodes" already exists
/generated-config/2024-09-06-05-32-57
Creating genesis configmap in k8s ...
Error from server (NotFound): configmaps "besu-genesis" not found
configmap/besu-genesis created
Creating validator secrets in k8s ...
validator3
Creating keys in vault for validator-1 ...
secret/besu-node-validator-1-keys created
configmap/besu-node-validator-1-address created
validator2
Creating keys in vault for validator-2 ...
secret/besu-node-validator-2-keys created
configmap/besu-node-validator-2-address created
validator1
Creating keys in vault for validator-3 ...
secret/besu-node-validator-3-keys created
configmap/besu-node-validator-3-address created
validator0
Creating keys in vault for validator-4 ...
secret/besu-node-validator-4-keys created
configmap/besu-node-validator-4-address created
Error from server (NotFound): configmaps "besu-peers" not found
configmap/besu-peers created
Completed ...
```

**Comment by Params10** [comment]
Thank you for your response, While I added sleep it worked fine with my script.
