### ISSUE TITLE
request for deployment to privately configured Kubernates Clusters

### ISSUE THREAD

**Issue by pennuel** [Consensys/quorum-kubernetes#247]

**Comment by joshuafernandes** [comment]
Hello @pennuel 

I think for a privately configured cluster outside of AWS/Azure you can use the [playground](https://github.com/Consensys/quorum-kubernetes/tree/master/playground) or set the helm charts to `provider: local` https://github.com/Consensys/quorum-kubernetes/tree/master/helm#helm-charts Essentially you are treating it no different to that of minikube or the like and you can customise anything to suit your custom configuration

Cheers
Josh
