### ISSUE TITLE
Error calling include: templateerror calling include: template:: no template "goquorum-genesis.name" associated with template "gotpl"

### ISSUE THREAD

**Issue by andyafene** [ConsenSys/quorum-kubernetes#94]
Hello,

I'm following the guide to run Hyperledger Besu or GoQuorum clients in Azure AKS (Kubernetes) for a production scenario. 
Here are the steps that I followed:
1. In all providers, I replaced **aws** to **azure**
2. In **quorum-kubernetes/prod/helm/charts/goquorum-node/templates/node-statefulset.yaml** I replaced ````quorum-node.fullname```` to ````goquorum-node.fullname````  https://github.com/ConsenSys/quorum-kubernetes/blob/252ccd7763301af345df953134ef0bc1d134e80a/prod/helm/charts/goquorum-node/templates/node-statefulset.yaml#L41

3. In **quorum-kubernetes/azure/arm/azuredeploy** I replaced **dev** to **prod**
https://github.com/ConsenSys/quorum-kubernetes/blob/252ccd7763301af345df953134ef0bc1d134e80a/azure/arm/azuredeploy.json#L7

Here is the error that I get after running the following command : ````helm install validator-1 ./charts/goquorum-node --namespace quorum --values ./values/validator.yml````
````
Error: template: goquorum-node/templates/node-statefulset.yaml:145:29: executing "goquorum-node/templates/node-statefulset.yaml" at <include "goquorum-genesis.name" .>: error calling include: templateerror calling include: template:: no template "goquorum-genesis.name" associated with template "gotpl"
````

Can you help me?

**Comment by joshuafernandes** [comment]
Hi @andyafene 

Could you explain what is being done in step 2 please? The charts work as is 

I would suggest you run the `dev` charts first and make sure things are working correctly.

Then follow the steps to setup the cluster for prod including the prerequisites and the scripts here https://github.com/ConsenSys/quorum-kubernetes/tree/master/azure - the prod charts use features that need to be enabled.

Then follow the steps listed here in the `For GoQuorum` section by:
1. editing not just the provider but also the azure section in all the values.yml
2. Then deploy per the instructions here : https://github.com/ConsenSys/quorum-kubernetes/blob/master/prod/README.md

**Comment by YounesBM** [comment]
Hello @joshuafernandes :)

Thank you very much for your reply.

I am working with Andy on the same project.

I saw the fixes you made to the dev environment. I had already understood the namespace problem that prevented us from deploying the dev. Everything is working fine at this level.
I just want to point out that you forgot to remove the --create-namespace in the README.md, when using the command :
`helm install genesis ./charts/goquorum-genesis --namespace quorum --create-namespace --values ./values/genesis-goquorum.yml`
The namespace "quorum" is already created with the first command:
`helm install monitoring ./charts/quorum-monitoring --namespace quorum --create-namespace`

We now have a problem when deploying the prod environment to Azure. The genesis-job.yaml does not work because of an issuer problem for writing keys in the keyvault. Here are the genesis pod logs:

[https://github.com/YounesBM/logs-quorum/blob/main/logs.txt](url)

We tried adding all possible access policies, but that did not solve the problem. I can't even list the keys, secrets and certificates of the keyvault even though I am an owner of it. The identity pod is also an owner of the keyvault.

Do you have a workaround?

Best Regards,

Younes

**Comment by joshuafernandes** [comment]
Hi @YounesBM 

Thats good :)

If the namespace sorted out prom/grafana can I close the other issue #95 ?

Re this one, it looks like a cross tenancy issue from those logs. I'm not 100% certain of this but could you add the following after the login in line 116 https://github.com/ConsenSys/quorum-kubernetes/blob/master/prod/helm/charts/goquorum-genesis/templates/genesis-job.yaml#L117

```az account set --subscription <subscription name or id>
```
and then deploy please? Let me know if this works and I'll add this in to the charts

It looks like its trying to act on a subscription that it's not allowed to or something similar - if this doesn't work you will likely need to get in touch with MSFT support.

Re access to the keys, the way the template is currently setup is per best practices with least priveleges ie the keyvault is only accessible inside the VNet per the policies defined. The idea is this is restricted to only trusted admins and you can add more to suit your needs https://github.com/ConsenSys/quorum-kubernetes/blob/master/azure/arm/azuredeploy.json#L190. This is why you can't see, list anything in there. If you were on a VM inside the VNet though and had access to the vault you should be fine.

When I get back after the Christmas and New Year break, I'll be doing some doco and will have a bunch of screenshots that you can follow to make this easier.

Have a blessed Christmas and New Year!

Cheers

**Comment by andyafene** [comment]
Hello @joshuafernandes,

Thank you very much!
Everything works fine after adding the line and deploying!

Yes, you can close the other issue #95.

I wish you a merry Christmas and a happy New Year!

Regards,

Andy

**Comment by YounesBM** [comment]
Hello Joshua,

You made our day, thank you !

Merry Christmas and happy New year !

Cheers :)

Younes

**Comment by YounesBM** [comment]
Hello Joshua,

I hope you had a great holiday season and I wish you all the best for 2022.

We have good news, we have successfully deployed the prod. We had forgotten to change all the values in the folder /prod/helm/values.
However, we noticed that the genesis.json comes from an image published on docker hub at this address :
https://hub.docker.com/r/consensys/istanbul-tools
We would like to customize this genesis.json to create our own test accounts and provision them as we want.

Can you please make the content of the docker image public?

Thank you very much and happy new year,

Best Regards,

Younes

**Comment by joshuafernandes** [comment]
Hi @YounesBM 

Really good to hear :) Happy New Year! Wish you all the best for 2022 and hope you had a good break as well. 

Yep that is a limitation at the moment, and is based on https://github.com/getamis/istanbul-tools which creates the artifacts. We're working on a new tool which will allow you to do this as well as be a single tool for both Besu and GoQuorum so will update this repo to use that when we release - and can keep you posted when this happens

Have a great day

Cheers
Josh

**Comment by joshuafernandes** [comment]
Should be sorted now with PR-98
