### ISSUE TITLE
503 error code after running commands to connect to Graphana and Prometeus

### ISSUE THREAD

**Issue by andyafene** [ConsenSys/quorum-kubernetes#95]
Hello,

I followed the guide to run Hyperledger Besu or GoQuorum clients in Azure AKS (Kubernetes) for a dev scenario.

In order to connect to Graphana and Prometeus, I ran the following commands:  
````
# For Besu's grafana address:
http://<INGRESS_IP>/d/XE4V0WGZz/besu-overview?orgId=1&refresh=10s
# For GoQuorum's grafana address:
http://<INGRESS_IP>/d/a1lVy7ycin9Yv/goquorum-overview?orgId=1&refresh=10s
````
For some reason, I get a **503 Error code** after running them. 
However, with the same Ip adress, I can reach the API, with the following command:
````
curl -v -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://<INGRESS_IP>/rpc
````
I still don't know what I'm doing wrong. Can you help me? Please.

Regards,

**Comment by joshuafernandes** [comment]
Hi @andyafene did you deploy the monitoring charts? And can you confirm they are running please in the logs

**Comment by joshuafernandes** [comment]
You also need to deploy the appropriate set of ingress rules

**Comment by joshuafernandes** [comment]
Closing as per comments in #95
