### ISSUE TITLE
Playground Besu ethash example lacks instructions on creating genesis.json and deploy-with-miner.sh script

### ISSUE THREAD

**Issue by paul-snively** [ConsenSys/quorum-kubernetes#97]
In `README.md` we find:

```markdown
#### 2. Genesis.json
Create the genesis.json file and copy its contents into the configmap/configmap as shown
```
with no further instructions, and

```markdown
# optionally deploy with miner
./deploy-with-miner.sh
```

but there is no `deploy-with-miner.sh` script in the subtree.

**Comment by joshuafernandes** [comment]
Hi @paul-snively 
Thanks for raising this. I've updated the readme and pushed a change with #99 

The process is similar to that of the tutorial here https://besu.hyperledger.org/en/latest/Tutorials/Private-Network/Create-Private-Network/

Let us know how you go 

Cheers
